project:
  type: website

website:
  title: "<img src='/images/logo.png' style='height:40px;'>"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3a"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03a.html"
          - text: "Hands-on Exercise 3b"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.html" 
          - text: "Hands-on Exercise 4a"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04a.html"
          - text: "Hands-on Exercise 4b"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.html"  
          - text: "Hands-on Exercise 4c"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.html"
          - text: "Hands-on Exercise 4d"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04d.html"   

      - text: "In-Class Exercise"
        menu:
          - text: "In-Class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "In-Class Exercise 3"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"  
            
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 2"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
          - text: "Take-home Exercise 3"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"

      - text: "Group Project"
        href: ""
            
            
    right:
      - about.qmd    
      - href: index.qmd
        text: "<img src='/images/home.png' style='height:25px;'>"

    
    after:
      - text: |
          <div class="announcement-bar">
            <div class="announcement-content">
              🔔 <strong>NEW (29/04)</strong> –
              <a href="Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03a.html">Exercise 3a</a> and
              <a href="Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.html">Exercise 3b</a> are published!
            </div>
          </div>

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    smooth-scroll: true

editor: visual

