{
  "hash": "35b1206f6d79c21d8980300f7e9c1482",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 2\"\nsubtitle: \" VAST Challenge 2025 Mini-Challenge 3\"\nauthor: \"Li Yuquan\"\ndescription: \"\"\ndate: \"May 11, 2025\"\ndate-modified: \"last-modified\"\nformat: html\nimage: images/fm.png\neditor: visual\n\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n\n\n# 1 Overview\n\nIn this report, I will be tacking [Mini-case 3](https://vast-challenge.github.io/2025/MC3.html) of [VAST Challenge 2025](https://vast-challenge.github.io/2025/index.html).\n\n## 1.1 Background\n\nOver the past decade, the Oceanus community has transitioned from its fishing-based roots to more regulated sectors like ocean tourism, following major crackdowns on illegal fishing. This shift has heightened local tensions. Recently, international pop star Sailor Shift announced plans to film a music video on the island, adding to the complexity.\n\nJournalist Clepper Jessen (formerly an analyst at FishEye, now with the Hacklee Herald) has been investigating the temporary closure of Nemo Reef. By analyzing intercepted radio communications and other data, he uncovered a tangled web involving high-ranking officials, Sailor Shift’s team, powerful local families, and the environmental group The Green Guardians, pointing toward corruption and manipulation.\n\n## 1.2 Tasks and Questions\n\nClepper diligently recorded all intercepted radio communications over the last two weeks. With the help of his intern, they have analyzed their content to identify important events and relationships between key players. The result is a knowledge graph describing the last two weeks on Oceanus. Clepper and his intern have spent a large amount of time generating this knowledge graph, and they would now like some assistance using it to answer the following questions.\n\nClepper found that messages frequently came in at around the same time each day.\n\n1.  Develop a graph-based visual analytics approach to identify any daily temporal patterns in communications.\n\n2.  How do these patterns shift over the two weeks of observations?\n\n3.  Focus on a specific entity and use this information to determine who has influence over them.\n\n## 1.3 The Data\n\nWe will use the dataset provided by VAST Challenge.This report utilizes two core datasets: MC3_graph.json, which encodes the knowledge graph of communications, events, and relationships; and MC3_schema.json, which defines the structure, subtypes, and attributes of each node and edge type within the graph.\n\n#### Node Attributes\n\n![](images/Screenshot%202025-05-29%20at%2010.31.09.png)\n\n#### Edge Attributes\n\n![](images/Screenshot%202025-05-29%20at%2012.27.36.png)\n\n# 2 Setup\n\n## 2.1 Loading Packages\n\n:::panel-tabset\n\n### The Table\n\n| Library        | Purpose                                                                                                                                       |\n|---------------|----------------------------------------------------------------------------------------------------------------------------------------------|\n| `jsonlite`    | An R package for parsing and generating JSON data, enabling smooth data exchange between R and web services or JSON files.                   |\n| `tidyverse`   | Include dplyr for data manipulation (mutate, group_by, summarize), ggplot2 for visualization (histograms, boxplots), and forcats for factor handling and variable ordering. |\n| `lubridate`   | An R package to work with dates and times, simplifying parsing, manipulation, and arithmetic of date-time objects.                           |\n| `patchwork`   | An R package for preparing composite figure created using ggplot2.                                                                           |\n| `ggridges`    | An R package for creating density plots for visualisation of continuous distribution.                                                         |\n| `ggraph`      | An R package extending ggplot2 to visualize graph/network data, supporting layouts like force-directed, circular, and dendrograms.           |\n| `tidygraph`   | An R package that integrates tidyverse principles into graph/network analysis, allowing tidy manipulation of graph objects.                  |\n| `igraph`      | A core R package for network analysis and visualization, providing tools to create, manipulate, and analyze graph structures.                |\n| `dplyr`       | Part of the tidyverse; provides fast, consistent functions for data manipulation (filter, select, mutate, summarize, join).                  |\n| `ggiraph`     | An R package to create interactive ggplot-based visualizations with tooltips, hover effects, and JavaScript interactions.                    |\n| `SmartEDA`    | An R package providing automated exploratory data analysis (EDA) tools to quickly summarize and visualize datasets.                          |\n| `visNetwork`  | An R package for interactive network visualization using the vis.js JavaScript library, enabling interactive exploration of graph data.      |\n\n### The Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(\n  jsonlite,\n  tidyverse,\n  lubridate,\n  patchwork,\n  ggridges,\n  ggraph,\n  tidygraph,\n  igraph,\n  dplyr,\n  ggiraph,\n  SmartEDA,\n  visNetwork,\n  ggiraph\n)\n```\n:::\n\n\n:::\n\n\n## 2.2 Importing data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMC3 <- fromJSON(\"data/MC3_graph.json\")\nMC3_schema <- fromJSON(\"data/MC3_schema.json\")\n```\n:::\n\n\n\n## 2.3 Data Overview\n\n::: panel-tabset\n### graph\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(MC3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 5\n $ directed  : logi TRUE\n $ multigraph: logi FALSE\n $ graph     :List of 4\n  ..$ mode        : chr \"static\"\n  ..$ edge_default: Named list()\n  ..$ node_default: Named list()\n  ..$ name        : chr \"VAST_MC3_Knowledge_Graph\"\n $ nodes     :'data.frame':\t1159 obs. of  31 variables:\n  ..$ type             : chr [1:1159] \"Entity\" \"Entity\" \"Entity\" \"Entity\" ...\n  ..$ label            : chr [1:1159] \"Sam\" \"Kelly\" \"Nadia Conti\" \"Elise\" ...\n  ..$ name             : chr [1:1159] \"Sam\" \"Kelly\" \"Nadia Conti\" \"Elise\" ...\n  ..$ sub_type         : chr [1:1159] \"Person\" \"Person\" \"Person\" \"Person\" ...\n  ..$ id               : chr [1:1159] \"Sam\" \"Kelly\" \"Nadia Conti\" \"Elise\" ...\n  ..$ timestamp        : chr [1:1159] NA NA NA NA ...\n  ..$ monitoring_type  : chr [1:1159] NA NA NA NA ...\n  ..$ findings         : chr [1:1159] NA NA NA NA ...\n  ..$ content          : chr [1:1159] NA NA NA NA ...\n  ..$ assessment_type  : chr [1:1159] NA NA NA NA ...\n  ..$ results          : chr [1:1159] NA NA NA NA ...\n  ..$ movement_type    : chr [1:1159] NA NA NA NA ...\n  ..$ destination      : chr [1:1159] NA NA NA NA ...\n  ..$ enforcement_type : chr [1:1159] NA NA NA NA ...\n  ..$ outcome          : chr [1:1159] NA NA NA NA ...\n  ..$ activity_type    : chr [1:1159] NA NA NA NA ...\n  ..$ participants     : int [1:1159] NA NA NA NA NA NA NA NA NA NA ...\n  ..$ thing_collected  :'data.frame':\t1159 obs. of  2 variables:\n  .. ..$ type: chr [1:1159] NA NA NA NA ...\n  .. ..$ name: chr [1:1159] NA NA NA NA ...\n  ..$ reference        : chr [1:1159] NA NA NA NA ...\n  ..$ date             : chr [1:1159] NA NA NA NA ...\n  ..$ time             : chr [1:1159] NA NA NA NA ...\n  ..$ friendship_type  : chr [1:1159] NA NA NA NA ...\n  ..$ permission_type  : chr [1:1159] NA NA NA NA ...\n  ..$ start_date       : chr [1:1159] NA NA NA NA ...\n  ..$ end_date         : chr [1:1159] NA NA NA NA ...\n  ..$ report_type      : chr [1:1159] NA NA NA NA ...\n  ..$ submission_date  : chr [1:1159] NA NA NA NA ...\n  ..$ jurisdiction_type: chr [1:1159] NA NA NA NA ...\n  ..$ authority_level  : chr [1:1159] NA NA NA NA ...\n  ..$ coordination_type: chr [1:1159] NA NA NA NA ...\n  ..$ operational_role : chr [1:1159] NA NA NA NA ...\n $ edges     :'data.frame':\t3226 obs. of  5 variables:\n  ..$ id         : chr [1:3226] \"2\" \"3\" \"5\" \"3013\" ...\n  ..$ is_inferred: logi [1:3226] TRUE FALSE TRUE TRUE TRUE TRUE ...\n  ..$ source     : chr [1:3226] \"Sam\" \"Sam\" \"Sam\" \"Sam\" ...\n  ..$ target     : chr [1:3226] \"Relationship_Suspicious_217\" \"Event_Communication_370\" \"Event_Assessment_600\" \"Relationship_Colleagues_430\" ...\n  ..$ type       : chr [1:3226] NA \"sent\" NA NA ...\n```\n\n\n:::\n:::\n\n\n\n### schema\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(MC3_schema)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 1\n $ schema:List of 2\n  ..$ nodes:List of 3\n  .. ..$ Entity      :List of 2\n  .. ..$ Event       :List of 2\n  .. ..$ Relationship:List of 2\n  ..$ edges:List of 3\n  .. ..$ description: chr \"Connections between nodes in the knowledge graph\"\n  .. ..$ is_inferred: chr \"bool\"\n  .. ..$ types      :'data.frame':\t6 obs. of  5 variables:\n```\n\n\n:::\n:::\n\n\n:::\n\n## 2.4 Extracting Nodes and Edges\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc3_nodes <- as_tibble(MC3$nodes)\nmc3_edges <- as_tibble(MC3$edges)\n```\n:::\n\n\n\n### 2.4.1 Overview for nodes & edges\n\n::: panel-tabset\n#### nodes\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(mc3_nodes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 31\n  type   label   name  sub_type id    timestamp monitoring_type findings content\n  <chr>  <chr>   <chr> <chr>    <chr> <chr>     <chr>           <chr>    <chr>  \n1 Entity Sam     Sam   Person   Sam   <NA>      <NA>            <NA>     <NA>   \n2 Entity Kelly   Kelly Person   Kelly <NA>      <NA>            <NA>     <NA>   \n3 Entity Nadia … Nadi… Person   Nadi… <NA>      <NA>            <NA>     <NA>   \n4 Entity Elise   Elise Person   Elise <NA>      <NA>            <NA>     <NA>   \n5 Entity Liam T… Liam… Person   Liam… <NA>      <NA>            <NA>     <NA>   \n6 Entity Samant… Sama… Person   Sama… <NA>      <NA>            <NA>     <NA>   \n# ℹ 22 more variables: assessment_type <chr>, results <chr>,\n#   movement_type <chr>, destination <chr>, enforcement_type <chr>,\n#   outcome <chr>, activity_type <chr>, participants <int>,\n#   thing_collected <df[,2]>, reference <chr>, date <chr>, time <chr>,\n#   friendship_type <chr>, permission_type <chr>, start_date <chr>,\n#   end_date <chr>, report_type <chr>, submission_date <chr>,\n#   jurisdiction_type <chr>, authority_level <chr>, coordination_type <chr>, …\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(mc3_nodes$type)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      Entity        Event Relationship \n          72          802          285 \n```\n\n\n:::\n:::\n\n\n\n#### edges\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(mc3_edges)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  id    is_inferred source target                      type \n  <chr> <lgl>       <chr>  <chr>                       <chr>\n1 2     TRUE        Sam    Relationship_Suspicious_217 <NA> \n2 3     FALSE       Sam    Event_Communication_370     sent \n3 5     TRUE        Sam    Event_Assessment_600        <NA> \n4 3013  TRUE        Sam    Relationship_Colleagues_430 <NA> \n5 <NA>  TRUE        Sam    Relationship_Friends_272    <NA> \n6 <NA>  TRUE        Sam    Relationship_Colleagues_215 <NA> \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(mc3_edges$type)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nevidence_for     received         sent \n        1036          584          584 \n```\n\n\n:::\n:::\n\n\n:::\n\n## 2.5 Initial EDA\n\n:::: panel-tabset\n### nodes\n\nIn the code chunk below, `ExpCatViz()` of SmartEDA package is used to reveal the frequency distribution of all categorical fields in *mc3_nodes* tibble dataframe.\n\n::: panel-tabset\n#### The Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nExpCatViz(data=mc3_nodes,\n          col=\"lightblue\")\n```\n:::\n\n\n\n#### The Plot\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[2]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-11-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[3]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-11-3.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[4]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-11-4.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[5]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-11-5.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[6]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-11-6.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[7]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-11-7.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[8]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-11-8.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[9]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-11-9.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[10]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-11-10.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[11]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-11-11.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[12]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-11-12.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[13]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-11-13.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[14]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-11-14.png){width=672}\n:::\n:::\n\n\n:::\n\n### edges\n\nThe code chunk below uses ExpCATViz() of SmartEDA package to reveal the frequency distribution of all categorical fields in mc3_edges tibble dataframe.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nExpCatViz(data=mc3_edges,\n          col=\"lightblue\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n::::\n\n# 3 Data Wrangling\n\n## 3.1 Node Cleaning\n\nConvert node table id to character type, remove missing and duplicate rows, and drop the unnecessary thing_collected column.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc3_nodes_cleaned <- mc3_nodes %>%\n  mutate(id = as.character(id)) %>%\n  filter(!is.na(id)) %>%\n  distinct(id, .keep_all = TRUE) %>%\n  select(-thing_collected)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(mc3_nodes_cleaned)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 30\n  type   label   name  sub_type id    timestamp monitoring_type findings content\n  <chr>  <chr>   <chr> <chr>    <chr> <chr>     <chr>           <chr>    <chr>  \n1 Entity Sam     Sam   Person   Sam   <NA>      <NA>            <NA>     <NA>   \n2 Entity Kelly   Kelly Person   Kelly <NA>      <NA>            <NA>     <NA>   \n3 Entity Nadia … Nadi… Person   Nadi… <NA>      <NA>            <NA>     <NA>   \n4 Entity Elise   Elise Person   Elise <NA>      <NA>            <NA>     <NA>   \n5 Entity Liam T… Liam… Person   Liam… <NA>      <NA>            <NA>     <NA>   \n6 Entity Samant… Sama… Person   Sama… <NA>      <NA>            <NA>     <NA>   \n# ℹ 21 more variables: assessment_type <chr>, results <chr>,\n#   movement_type <chr>, destination <chr>, enforcement_type <chr>,\n#   outcome <chr>, activity_type <chr>, participants <int>, reference <chr>,\n#   date <chr>, time <chr>, friendship_type <chr>, permission_type <chr>,\n#   start_date <chr>, end_date <chr>, report_type <chr>, submission_date <chr>,\n#   jurisdiction_type <chr>, authority_level <chr>, coordination_type <chr>,\n#   operational_role <chr>\n```\n\n\n:::\n:::\n\n\n\n## 3.2 Edge Cleaning\n\nRename source and target fields, ensure both are character type, and filter out edges without valid from_id or to_id.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc3_edges_cleaned <- mc3_edges %>%\n  rename(from_id = source, to_id = target) %>%\n  mutate(across(c(from_id, to_id), as.character)) %>%\n  filter(from_id %in% mc3_nodes_cleaned$id, to_id %in% mc3_nodes_cleaned$id) %>%\n  filter(!is.na(from_id), !is.na(to_id))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(mc3_edges_cleaned)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  id    is_inferred from_id to_id                       type \n  <chr> <lgl>       <chr>   <chr>                       <chr>\n1 2     TRUE        Sam     Relationship_Suspicious_217 <NA> \n2 3     FALSE       Sam     Event_Communication_370     sent \n3 5     TRUE        Sam     Event_Assessment_600        <NA> \n4 3013  TRUE        Sam     Relationship_Colleagues_430 <NA> \n5 <NA>  TRUE        Sam     Relationship_Friends_272    <NA> \n6 <NA>  TRUE        Sam     Relationship_Colleagues_215 <NA> \n```\n\n\n:::\n:::\n\n\n\n## 3.3 Create Node Index Mapping\n\nGenerate a .row_id sequence for the cleaned nodes to use as a numeric index for replacing character IDs.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnode_index_lookup <- mc3_nodes_cleaned %>%\n  mutate(.row_id = row_number()) %>%\n  select(id, .row_id)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(node_index_lookup)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  id             .row_id\n  <chr>            <int>\n1 Sam                  1\n2 Kelly                2\n3 Nadia Conti          3\n4 Elise                4\n5 Liam Thorne          5\n6 Samantha Blake       6\n```\n\n\n:::\n:::\n\n\n\n## 3.4 Replace Edge IDs with Indices\n\nJoin edges with the node index lookup table to replace from_id and to_id with their corresponding numeric indices.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc3_edges_indexed <- mc3_edges_cleaned %>%\n  left_join(node_index_lookup, by = c(\"from_id\" = \"id\")) %>%\n  rename(from = .row_id) %>%\n  left_join(node_index_lookup, by = c(\"to_id\" = \"id\")) %>%\n  rename(to = .row_id) %>%\n  select(from, to, is_inferred, type) %>%\n  filter(!is.na(from) & !is.na(to))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(mc3_edges_indexed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n   from    to is_inferred type \n  <int> <int> <lgl>       <chr>\n1     1  1138 TRUE        <NA> \n2     1   357 FALSE       sent \n3     1   747 TRUE        <NA> \n4     1   895 TRUE        <NA> \n5     1   876 TRUE        <NA> \n6     1   888 TRUE        <NA> \n```\n\n\n:::\n:::\n\n\n\n## 3.5 Subset Used Nodes\n\nKeep only the nodes that are actually referenced in the edge list and assign them new consecutive indices.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nused_node_indices <- sort(unique(c(mc3_edges_indexed$from, mc3_edges_indexed$to)))\n\nmc3_nodes_final <- mc3_nodes_cleaned %>%\n  slice(used_node_indices) %>%\n  mutate(new_index = row_number())\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(mc3_nodes_final)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 31\n  type   label   name  sub_type id    timestamp monitoring_type findings content\n  <chr>  <chr>   <chr> <chr>    <chr> <chr>     <chr>           <chr>    <chr>  \n1 Entity Sam     Sam   Person   Sam   <NA>      <NA>            <NA>     <NA>   \n2 Entity Kelly   Kelly Person   Kelly <NA>      <NA>            <NA>     <NA>   \n3 Entity Nadia … Nadi… Person   Nadi… <NA>      <NA>            <NA>     <NA>   \n4 Entity Elise   Elise Person   Elise <NA>      <NA>            <NA>     <NA>   \n5 Entity Liam T… Liam… Person   Liam… <NA>      <NA>            <NA>     <NA>   \n6 Entity Samant… Sama… Person   Sama… <NA>      <NA>            <NA>     <NA>   \n# ℹ 22 more variables: assessment_type <chr>, results <chr>,\n#   movement_type <chr>, destination <chr>, enforcement_type <chr>,\n#   outcome <chr>, activity_type <chr>, participants <int>, reference <chr>,\n#   date <chr>, time <chr>, friendship_type <chr>, permission_type <chr>,\n#   start_date <chr>, end_date <chr>, report_type <chr>, submission_date <chr>,\n#   jurisdiction_type <chr>, authority_level <chr>, coordination_type <chr>,\n#   operational_role <chr>, new_index <int>\n```\n\n\n:::\n:::\n\n\n\n## 3.6 Create Old-to-New Index Mapping\n\nCreate a lookup table that maps old node indices to the new consecutive indices for consistent edge alignment.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nold_to_new_index <- tibble(\n  old_index = used_node_indices,\n  new_index = seq_along(used_node_indices)\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(old_to_new_index)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  old_index new_index\n      <int>     <int>\n1         1         1\n2         2         2\n3         3         3\n4         4         4\n5         5         5\n6         6         6\n```\n\n\n:::\n:::\n\n\n\n## 3.7 Update Edge Indices\n\nUpdate the edge list by replacing old indices with the new consecutive indices, ensuring alignment with the final node table.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc3_edges_final <- mc3_edges_indexed %>%\n  left_join(old_to_new_index, by = c(\"from\" = \"old_index\")) %>%\n  rename(from_new = new_index) %>%\n  left_join(old_to_new_index, by = c(\"to\" = \"old_index\")) %>%\n  rename(to_new = new_index) %>%\n  select(from = from_new, to = to_new, is_inferred, type)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(mc3_edges_final)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n   from    to is_inferred type \n  <int> <int> <lgl>       <chr>\n1     1  1138 TRUE        <NA> \n2     1   357 FALSE       sent \n3     1   747 TRUE        <NA> \n4     1   895 TRUE        <NA> \n5     1   876 TRUE        <NA> \n6     1   888 TRUE        <NA> \n```\n\n\n:::\n:::\n\n\n\n## 3.8 Build Graph Object\n\nConstruct a directed graph using the tidygraph package, combining the cleaned node and edge tables for network analysis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc3_graph <- tbl_graph(\n  nodes = mc3_nodes_final,\n  edges = mc3_edges_final,\n  directed = TRUE\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(mc3_graph)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n6 x 1159 sparse Matrix of class \"dgCMatrix\"\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . 1 . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . 1 . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . 1 . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . 1 . 1 . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . 1 . . . . . 1 . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . 1 . . 1 . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . 1 . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . 1 . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . 1 . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . 1 . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 1 .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 1 . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 1\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . 1 . 1 . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . 1 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . 1 . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    1 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . 1 . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . 1 . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . 1 . . . . . . . . . . . . . . . . . . . . . . . . . . 1 .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . 1 . . . . . . . . . 1 . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . 1 . . . . . . . . 1 . . . . 1 .\nSamantha Blake 1 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 1 . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    1 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 1\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . 1 . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . 1 . . . . . . . . . . 1 . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . 1 . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . 1 . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . 1 . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 1 .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . 1 . . . . . . . . . . . 1 . . . . . . 1 1\nKelly          . . . . . . . . . . . 1 . . . . . . . . . . . 1 . . . . . . . .\nNadia Conti    . . . 1 . . . . . . . . . . . . . . . . . . . . . 1 . 1 1 . . 1\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . 1 1 . . 1 .\nLiam Thorne    1 . . . . . . . . . . . . . . . . . . . . 1 . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    1 . . 1 . . . . . . . . . . . . . . . . . . . . . . . 1 . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    1 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . 1 . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . 1 . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . 1 . . . . . . . . . . . . . . . . . 1 . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . 1 . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . 1 . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . 1 . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . 1 . . . . . . . . . . . . . . . . . . . . .\nElise          . . . 1 . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . 1 . . 1 . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . 1 . 1 . . . . . . . .\n                                                                              \nSam            . . . . . . . . . . . . . . . . . 1 . . . . . . . . . . . . . .\nKelly          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nNadia Conti    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\nElise          . . . . . . . . . . . . . . . . . . . . . . . 1 . . . . . . . .\nLiam Thorne    . . . . . . . . . . . . . . . . . . . . . 1 . . . . . 1 . . . .\nSamantha Blake . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n                            \nSam            . . . . . . .\nKelly          . . . . . . .\nNadia Conti    . . . . . . .\nElise          . . . . . . .\nLiam Thorne    . . . . . . .\nSamantha Blake . . . 1 . . .\n```\n\n\n:::\n:::\n\n\n\n## 3.9 Extract Node and Edge Tables\n\nConvert the graph object back into tidy nodes and edges tables for further data processing\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes <- as_tibble(mc3_graph, active = \"nodes\")\nedges <- as_tibble(mc3_graph, active = \"edges\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(nodes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 31\n  type   label   name  sub_type id    timestamp monitoring_type findings content\n  <chr>  <chr>   <chr> <chr>    <chr> <chr>     <chr>           <chr>    <chr>  \n1 Entity Sam     Sam   Person   Sam   <NA>      <NA>            <NA>     <NA>   \n2 Entity Kelly   Kelly Person   Kelly <NA>      <NA>            <NA>     <NA>   \n3 Entity Nadia … Nadi… Person   Nadi… <NA>      <NA>            <NA>     <NA>   \n4 Entity Elise   Elise Person   Elise <NA>      <NA>            <NA>     <NA>   \n5 Entity Liam T… Liam… Person   Liam… <NA>      <NA>            <NA>     <NA>   \n6 Entity Samant… Sama… Person   Sama… <NA>      <NA>            <NA>     <NA>   \n# ℹ 22 more variables: assessment_type <chr>, results <chr>,\n#   movement_type <chr>, destination <chr>, enforcement_type <chr>,\n#   outcome <chr>, activity_type <chr>, participants <int>, reference <chr>,\n#   date <chr>, time <chr>, friendship_type <chr>, permission_type <chr>,\n#   start_date <chr>, end_date <chr>, report_type <chr>, submission_date <chr>,\n#   jurisdiction_type <chr>, authority_level <chr>, coordination_type <chr>,\n#   operational_role <chr>, new_index <int>\n```\n\n\n:::\n:::\n\n\n\n## 3.10 Process Time Fields and Filter Communication Nodes\n\nParse and convert date/time fields, extract hour and weekday, and filter the data to include only nodes of type Communication.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes <- nodes %>%\n  mutate(\n    timestamp = ymd_hms(timestamp, quiet = TRUE),\n    date = as.Date(timestamp),\n    start_date = ymd(start_date, quiet = TRUE),\n    end_date = ymd(end_date, quiet = TRUE),\n    submission_date = ymd(submission_date, quiet = TRUE),\n    hour = hour(timestamp),\n    weekday = wday(timestamp, label = TRUE)\n  )\n\ncomm_nodes <- nodes %>%\n  filter(sub_type == \"Communication\", !is.na(timestamp))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(comm_nodes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 33\n  type  label  name  sub_type id    timestamp           monitoring_type findings\n  <chr> <chr>  <chr> <chr>    <chr> <dttm>              <chr>           <chr>   \n1 Event Commu… <NA>  Communi… Even… 2040-10-01 08:09:00 <NA>            <NA>    \n2 Event Commu… <NA>  Communi… Even… 2040-10-01 08:10:00 <NA>            <NA>    \n3 Event Commu… <NA>  Communi… Even… 2040-10-01 08:13:00 <NA>            <NA>    \n4 Event Commu… <NA>  Communi… Even… 2040-10-01 08:16:00 <NA>            <NA>    \n5 Event Commu… <NA>  Communi… Even… 2040-10-01 08:19:00 <NA>            <NA>    \n6 Event Commu… <NA>  Communi… Even… 2040-10-01 08:21:00 <NA>            <NA>    \n# ℹ 25 more variables: content <chr>, assessment_type <chr>, results <chr>,\n#   movement_type <chr>, destination <chr>, enforcement_type <chr>,\n#   outcome <chr>, activity_type <chr>, participants <int>, reference <chr>,\n#   date <date>, time <chr>, friendship_type <chr>, permission_type <chr>,\n#   start_date <date>, end_date <date>, report_type <chr>,\n#   submission_date <date>, jurisdiction_type <chr>, authority_level <chr>,\n#   coordination_type <chr>, operational_role <chr>, new_index <int>, …\n```\n\n\n:::\n:::\n\n\n\n# 4 Data Prepaer for visualization\n\n## 4.1 Data Prepare for Sub-Question A\n\n`hourly_counts`: Groups the comm_nodes data by date and hour and calculates the total number of messages per hour, which is used to generate the heatmap plot (ap1).\n\n`violin_data`: Selects only the date, hour, and weekday columns to prepare data for the violin plot (ap2), which visualizes the density distribution of messages across hours.\n\n`daily_counts`: Groups by date and calculates the total number of messages per day, providing the basis for the daily line chart (ap4), and computes the overall average message count (avg_messages) to use as a reference line.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#ap1\nhourly_counts <- comm_nodes %>%\n  group_by(date, hour) %>%\n  summarise(message_count = n(), .groups = \"drop\")\n\n#ap2\nviolin_data <- comm_nodes %>%\n  select(date, hour, weekday)\n\n# ap4\ndaily_counts <- comm_nodes %>%\n  group_by(date) %>%\n  summarise(total_messages = n(), .groups = \"drop\")\n\navg_messages <- mean(daily_counts$total_messages)\n```\n:::\n\n\n\n## 4.2 Data Prepare for Sub-Question B\n\n`hourly_counts` (extend): Builds on the Sub-A dataset by adding a week label (splitting into Week 1 and Week 2) and computing weekday_num (using wday() with Monday as the start of the week). It then arranges the data by weekday_num and creates a factor date_factor for consistent date ordering in the heatmap plot (bp1).\n\n`weekly_hourly_counts`: Groups comm_nodes by week_group and hour and calculates the total message count per hour, used for the weekly comparison line plot (bp2) to visualize trends across hours between the two weeks.\n\n`violin_data_2` and `violin_data_2_filtered`: Expands the violin plot data by adding week and weekday labels and filters unique dates within each week, preparing data for the split-week violin distribution plot (bp3).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#bp1\nhourly_counts <- hourly_counts %>%\n  mutate(\n    week = ifelse(date <= as.Date(\"2040-10-07\"), \n                  \"Week 1 (Oct 1–7)\", \n                  \"Week 2 (Oct 8–14)\"),\n    weekday_num = wday(date, week_start = 1))\n\n\nhourly_counts <- hourly_counts %>%\n  group_by(week) %>%\n  arrange(weekday_num, .by_group = TRUE) %>%\n  mutate(date_factor = factor(date, levels = unique(date))) %>%\n  ungroup()\n\n\n#bp2\nsplit_date <- min(comm_nodes$date) + 6\ncomm_nodes <- comm_nodes %>%\n  mutate(week_group = if_else(date <= split_date, \"Week 1\", \"Week 2\"))\n\nweekly_hourly_counts <- comm_nodes %>%\n  group_by(week_group, hour) %>%\n  summarise(message_count = n(), .groups = \"drop\")\n\n#bp3\nviolin_data_2 <- comm_nodes %>%\n  mutate(\n    weekday = wday(date, label = TRUE, week_start = 1),\n    week = ifelse(date <= min(date) + 6, \"Week 1\", \"Week 2\")\n  ) %>%\n  select(week, date, weekday, hour)\n\nviolin_data_2_filtered <- violin_data_2 %>%\n  group_by(week) %>%\n  filter(date %in% unique(date))\n```\n:::\n\n\n\n## 4.3 Data Prepare for Sub-Question C\n\n`Overview Graph`—construct the full entity-to-entity graph by:\n\n-   Extracting sent and received edge types.\n\n-   Matching sent + received pairs to form communication edges. Adding additional one-way edges (sent only, received only) for a complete set.\n\n-   Filtering to retain only edges where both nodes are entities.\n\n-   Building the full directed graph (g), on which we compute centrality metrics like PageRank, betweenness, and degree.\n\n-   Extracting a 2-hop ego network (ego_graph) centered on Elise to visualize her local influence neighborhood. Ego Graph Preparation\n\n`ego network:`\n\n-   Using only the paired comm_edges (sent + received) between entities.\n\n-   Constructing a separate graph (g) for cleaner analysis.\n\n-   Extracting the 1-hop ego network (ego_1) around Elise.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#overview-graph\nsent_edges <- edges %>%\n  filter(type == \"sent\") %>%\n  select(source_entity = from, event = to)\n\nreceived_edges <- edges %>%\n  filter(type == \"received\") %>%\n  select(event = from, target_entity = to)\n\npaired_edges <- sent_edges %>%\n  inner_join(received_edges, by = \"event\") %>%\n  select(from = source_entity, to = target_entity)\n\nsingle_sent_edges <- sent_edges %>%\n  select(from = source_entity, to = event)\n\nsingle_received_edges <- received_edges %>%\n  select(from = event, to = target_entity)\n\nall_edges <- bind_rows(paired_edges, \n                       single_sent_edges, \n                       single_received_edges) %>%\n  distinct()\n\nentity_ids <- nodes %>%\n  filter(type == \"Entity\") %>%\n  pull(new_index) %>%\n  as.character()\n\nentity_edges <- all_edges %>%\n  filter(as.character(from) %in% entity_ids, \n         as.character(to) %in% entity_ids)\n\nentity_nodes <- nodes %>%\n  filter(type == \"Entity\") %>%\n  select(new_index, id, label, sub_type) %>%\n  mutate(new_index = as.character(new_index))\n\ng <- graph_from_data_frame(d = entity_edges, \n                           vertices = entity_nodes, \n                           directed = TRUE)\n\nV(g)$pagerank <- page_rank(g)$vector\nV(g)$betweenness <- betweenness(g)\nV(g)$degree <- degree(g)\n\ntarget_entity <- \"Elise\"\ntarget_index <- which(V(g)$label == target_entity)\nego_graph <- make_ego_graph(g, order = 2, \n                            nodes = target_index, mode = \"all\")[[1]]\n\n\n# ego-graph\n\ncomm_edges <- sent_edges %>%\n  inner_join(received_edges, by = \"event\") %>%\n  select(from = source_entity, to = target_entity)\n\nentity_nodes <- nodes %>%\n  filter(type == \"Entity\") %>%\n  select(new_index, id, label, sub_type)\n\ng <- graph_from_data_frame(d = comm_edges, \n                           vertices = entity_nodes, \n                           directed = TRUE)\n\ntarget_entity <- \"Elise\"\ntarget_index <- which(V(g)$label == target_entity)\nego_1 <- make_ego_graph(g, order = 1, nodes = target_index, mode = \"all\")[[1]]\n\nV(ego_1)$name <- V(ego_1)$name %||% V(ego_1)$label\n```\n:::\n\n\n\n# 5 Visualization For Mini-Challenge 3 Question 1\n\n## 5.1 Sub-Question A\n\n::: callout-note\n# Question for Sub-Question A\n\nDevelop a graph-based visual analytics approach to identify any daily temporal patterns in communications.\n:::\n\n::: panel-tabset\n### The Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-36-1.png){width=960}\n:::\n:::\n\n\n\n### The Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ap1\nap1 <- ggplot(hourly_counts, \n              aes(x = hour,\n                  y = factor(date), \n                  fill = message_count)) +\n  geom_tile(color = \"white\") +\n  geom_text(aes(label = message_count), \n            color = \"white\", size = 3) +\n  scale_fill_gradient(name = \"# of messages\", \n                      low = \"skyblue\", high = \"darkblue\") +\n  labs(title = \"Hourly Message Count by Day\", \n       x = \"Hour of Day\", \n       y = \"Date\") +\n  theme_minimal() +\n  scale_x_continuous(breaks = 0:23) + \n  scale_y_discrete(\n    labels = function(d) {\n      weekday <- comm_nodes %>%\n        filter(date == d) %>%\n        pull(weekday) %>%\n        unique()\n      paste0(d, \" (\", weekday, \")\")\n    }\n  ) +\n  theme(\n    legend.position = \"top\",\n    legend.direction = \"horizontal\",\n    legend.justification = c(1, 1),\n    legend.box.just = \"right\",\n    legend.title = element_text(size = 8),\n    legend.text = element_text(size = 6),\n    plot.title = element_text(hjust = 0.5)\n  )\n\n#ap2\nap2 <- ggplot(violin_data, aes(x = hour, \n                               y = factor(date), \n                               fill = factor(date))) +\n  geom_density_ridges(\n    alpha = 0.6,\n    scale = 1,\n    jittered_points = TRUE,\n    point_shape = \"·\",\n    point_size = 2.5,\n    position = \"raincloud\"\n  ) +\n  scale_x_continuous(limits = c(6, 14), \n                     breaks = 6:14) + \n  scale_y_discrete(\n    labels = function(d) {\n      weekday <- violin_data %>%\n        filter(date == d) %>%\n        pull(weekday) %>%\n        unique()\n      paste0(d, \" (\", weekday, \")\")\n    }\n  ) +\n  labs(\n    title = \"Hourly Message Distribution by Day\",\n    x = \"Hour of Day\",\n    y = \"Date\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n\n#ap3\nap3 <- ggplot(comm_nodes, aes(x = hour)) +\n  geom_density(fill = \"skyblue\", \n               alpha = 0.6) +\n  labs(\n    title = \"Hourly Message Density Across All Days\",\n    x = \"Hour of Day\",\n    y = \"Density\"\n  ) +\n  theme_minimal() +\n  scale_x_continuous(breaks = 0:23)\n\n#ap4\nap4 <- ggplot(daily_counts, aes(x = date, \n                                y = total_messages)) +\n  geom_line(color = \"mediumseagreen\", \n            size = 1) + \n  geom_point(color = \"mediumseagreen\", \n             size = 2) +\n  geom_hline(yintercept = avg_messages, \n             linetype = \"dashed\", \n             color = \"gray40\") +\n  annotate(\"text\", x = min(daily_counts$date), \n           y = avg_messages, \n           label = paste0(\"Avg: \", \n                          round(avg_messages, 1)),\n           hjust = 0, vjust = -0.5, \n           color = \"gray40\", size = 3) +\n  scale_x_date(\n    date_breaks = \"1 day\",\n    date_labels = \"%b %d\"\n  ) +\n  scale_y_continuous(\n    breaks = scales::pretty_breaks(n = 10)\n  ) +\n  labs(\n    title = \"Total Messages Per Day\",\n    x = \"Date\",\n    y = \"Total Messages\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(hjust = 0.5),\n    axis.text.x = element_text(angle = 45, hjust = 1)\n  )\n\n#plot\nap4 / ((ap1 / ap3) | ap2) + plot_layout(heights = c(0.5, 2))\n```\n:::\n\n\n:::\n\n::: {.callout-tip title=\"Insight\"}\n-   The daily communication volume fluctuates slightly between 34 and 49 messages, with an average of approximately 41.7 messages per day. Notably, October 11 records the highest peak (48 messages), following immediately after the lowest point on October 10 (35 messages), which may suggest a rapid rebound or intensified communication activity after a lull. Despite daily fluctuations, the overall message volume demonstrates strong stability.\n\n-   The time series charts using hourly intervals reveal a clear temporal rhythm: most communication activities are concentrated between 9:00 AM and 12:00 PM, with the peak occurring around 10:00 AM. After noon, the message frequency drops sharply, and on over half of the days, no communication takes place after 12:00 PM. This likely indicates that the involved parties follow a highly structured communication schedule, completing key messages, decisions, or approvals in the morning, leaving the rest of the day relatively quiet.\n\n-   The heatmap, offering a more granular hour-by-hour perspective, further pinpoints the peak morning communication window between 9:00 and 11:00 AM. For example, on October 5 (Friday), the 9:00 AM peak reaches 24 messages, while on October 13 (Sunday), the same time slot sees 19 messages. Most days repeatedly show deep blue tiles (indicating high intensity) between 8:00 and 11:00 AM, highlighting the systemic nature of the morning peaks.\n\n-   Overall, the communication pattern does not display a noticeable distinction between weekdays and weekends; for instance, on October 13 and October 14, which fall on a weekend, the volume of communications remains comparable to that on weekdays.\n:::\n\n## 5.2 Sub-Question B\n\n::: callout-note\n# Question for Sub-Question B\n\nHow do these patterns shift over the two weeks of observations?\n:::\n\n::: panel-tabset\n### The Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-38-1.png){width=960}\n:::\n:::\n\n\n\n### The Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#bp1\nbp1 <- ggplot(hourly_counts, \n                       aes(x = hour, \n                           y = date_factor, \n                           fill = message_count)) +\n  geom_tile(color = \"white\") +\n  geom_text(aes(label = message_count), \n            color = \"white\", size = 3) +\n  scale_fill_gradient(name = \"# of messages\", \n                      low = \"skyblue\", \n                      high = \"darkblue\") +\n  labs(title = \"Hourly Message Count by Day\", \n       x = \"Hour of Day\", y = \"Date\") +\n  facet_wrap(~ week, ncol = 1, scales = \"free_y\") +\n  scale_x_continuous(breaks = 0:23) + \n  scale_y_discrete(\n    limits = function(x) rev(x), \n    labels = function(d) {\n      weekday <- wday(as.Date(d), label = TRUE, \n                      week_start = 1)\n      paste0(d, \" (\", weekday, \")\")\n    }\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"top\",\n    legend.direction = \"horizontal\",\n    legend.title = element_text(size = 8),\n    legend.text = element_text(size = 6),\n    plot.title = element_text(hjust = 0.5)\n  )\n\n#bp2\nbp2 <- ggplot(weekly_hourly_counts, aes(x = hour, \n                                        y = message_count, \n                                        color = week_group)) +\n  geom_line(size = 1.2) +\n  geom_point(size = 2) +\n  labs(\n    title =\"    Hourly Message Trend by Week\",\n    x = \"Hour of Day\",\n    y = \"Total Messages\",\n    color = \"Week\"\n  ) +\n  theme_minimal() +\n  scale_x_continuous(breaks = 0:23)\n\n#bp3\nbp3 <- ggplot(violin_data_2_filtered, aes(x = hour, \n                                          y = fct_rev(paste0(date, \n                                                             \" (\", weekday, \")\")),\n                                          fill = weekday)) +\n  geom_density_ridges(\n    alpha = 0.6,\n    scale = 1,\n    jittered_points = TRUE,\n    point_shape = \"·\",\n    point_size = 2.5,\n    position = \"raincloud\"\n  ) +\n  scale_x_continuous(limits = c(6, 14), \n                     breaks = seq(6, 14, 2)) + \n  facet_wrap(~ week, ncol = 1, \n             scales = \"free_y\") + \n  labs(\n    title = \"Hourly Message Distribution by Weekday\",\n    x = \"Hour of Day\",\n    y = \"Date\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n\n#plot\n(bp2 / (bp1 | bp3) + plot_layout(heights = c(0.6, 2)))\n```\n:::\n\n\n:::\n\n::: {.callout-tip title=\"Insight\"}\n-   The line chart compares the hourly communication trends across the two weeks, showing that both weeks share a common peak at 10:00 AM. However, Week 1 (red line) shows a more prominent peak, reaching around 80 messages, while Week 2 (blue line) is slightly lower, at approximately 60 messages. After the 10 AM peak, the message volume drops sharply in both weeks, but Week 2 maintains slightly higher activity between 11 AM and 12 PM, indicating a marginally extended period of active communication compared to Week 1.\n\n-   The heatmap breaks down the hourly message counts by day. In Week 1, October 5 (Friday) stands out with an impressive 24 messages at 9 AM, while other days primarily concentrate between 8 AM and 11 AM. In Week 2, October 11 (Thursday) reaches the weekly peak with 21 messages at 10 AM, reflecting a slight shift toward later morning peaks.\n\n-   The ridgeline plot further highlights the shape of daily distributions. In Week 1, most days show sharp peaks centered around 9–10 AM. In contrast, Week 2 shows flatter and broader distributions on certain days (such as October 12–13, Friday–Saturday), indicating that communication activity extends further into the late morning. This suggests that Week 1’s communication was more concentrated in the early morning, while Week 2 exhibited a slightly prolonged morning communication window.\n\n-   Another notable change in the communication pattern is seen in the weekends: in Week 1, weekend communication peaks shifted later in the day and showed relatively smooth fluctuations, whereas in Week 2, the weekend communication peaks were more pronounced, concentrated at 8 AM and 12 PM respectively, showing a distinct difference from Week 1.\n:::\n\n## 5.3 Sub-Question C\n\n::: callout-note\n# Question for Sub-Question C\n\nFocus on a specific entity and use this information to determine who has influence over them.\n:::\n\n### 5.3.1 Overview\n\nTo investigate who has influence over the entity Elise, I combined global network visualizations with centrality-focused subgraphs centered on Elise.\n\nThe first global overview network graph (top image) provides the full knowledge graph of the Oceanus community, with nodes colored and shaped by entity type (Person, Organization, Vessel, Group, Location). From this high-level view, we observe that Elise is connected within a dense communication web, involving major actors such as Nadia Conti, V. Miesel Shipping, Neptune, and Mako. The node size visually indicates importance, with larger nodes corresponding to higher centrality measures.\n\n::: panel-tabset\n#### The Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-84b239ba8abf8eaaa8dd\" style=\"width:100%;height:700px;\" class=\"visNetwork html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-84b239ba8abf8eaaa8dd\">{\"x\":{\"nodes\":{\"id\":[\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"15\",\"16\",\"17\",\"18\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"31\",\"32\",\"33\",\"34\",\"36\",\"37\",\"40\",\"44\",\"45\",\"46\"],\"label\":[\"Nadia Conti\",\"Elise\",\"Liam Thorne\",\"Samantha Blake\",\"Davis\",\"Rodriguez\",\"Mrs. Money\",\"The Middleman\",\"Boss\",\"Small Fry\",\"Oceanus City Council\",\"Green Guardians\",\"V. Miesel Shipping\",\"Sailor Shifts Team\",\"Neptune\",\"Marlin\",\"Serenity\",\"Mako\",\"Reef Guardian\",\"Horizon\",\"EcoVigil\",\"Sentinel\",\"Osprey\",\"Defender\",\"Remora\",\"Knowles\",\"City Officials\",\"Paackland Harbor\",\"Haacklee Harbor\",\"Himark Harbor\"],\"group\":[\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Organization\",\"Organization\",\"Organization\",\"Organization\",\"Vessel\",\"Vessel\",\"Vessel\",\"Vessel\",\"Vessel\",\"Vessel\",\"Vessel\",\"Vessel\",\"Vessel\",\"Vessel\",\"Vessel\",\"Vessel\",\"Group\",\"Location\",\"Location\",\"Location\"],\"title\":[\"<b>Nadia Conti<\\/b><br>Degree: 17<br>Betweenness: 117.87<br>PageRank: 0.0432\",\"<b>Elise<\\/b><br>Degree: 7<br>Betweenness: 4.6<br>PageRank: 0.0182\",\"<b>Liam Thorne<\\/b><br>Degree: 11<br>Betweenness: 41.81<br>PageRank: 0.0275\",\"<b>Samantha Blake<\\/b><br>Degree: 6<br>Betweenness: 4.49<br>PageRank: 0.0114\",\"<b>Davis<\\/b><br>Degree: 16<br>Betweenness: 22.36<br>PageRank: 0.0239\",\"<b>Rodriguez<\\/b><br>Degree: 10<br>Betweenness: 11.75<br>PageRank: 0.0122\",\"<b>Mrs. Money<\\/b><br>Degree: 12<br>Betweenness: 167.18<br>PageRank: 0.0192\",\"<b>The Middleman<\\/b><br>Degree: 8<br>Betweenness: 50.78<br>PageRank: 0.0142\",\"<b>Boss<\\/b><br>Degree: 13<br>Betweenness: 136.18<br>PageRank: 0.0272\",\"<b>Small Fry<\\/b><br>Degree: 3<br>Betweenness: 0<br>PageRank: 0.0035\",\"<b>Oceanus City Council<\\/b><br>Degree: 28<br>Betweenness: 116.11<br>PageRank: 0.053\",\"<b>Green Guardians<\\/b><br>Degree: 17<br>Betweenness: 27.51<br>PageRank: 0.0224\",\"<b>V. Miesel Shipping<\\/b><br>Degree: 19<br>Betweenness: 118.7<br>PageRank: 0.0394\",\"<b>Sailor Shifts Team<\\/b><br>Degree: 7<br>Betweenness: 7.34<br>PageRank: 0.0186\",\"<b>Neptune<\\/b><br>Degree: 19<br>Betweenness: 82.59<br>PageRank: 0.0358\",\"<b>Marlin<\\/b><br>Degree: 10<br>Betweenness: 6.23<br>PageRank: 0.0235\",\"<b>Serenity<\\/b><br>Degree: 8<br>Betweenness: 0.81<br>PageRank: 0.017\",\"<b>Mako<\\/b><br>Degree: 37<br>Betweenness: 368.5<br>PageRank: 0.0687\",\"<b>Reef Guardian<\\/b><br>Degree: 27<br>Betweenness: 139.69<br>PageRank: 0.0454\",\"<b>Horizon<\\/b><br>Degree: 12<br>Betweenness: 6.72<br>PageRank: 0.0152\",\"<b>EcoVigil<\\/b><br>Degree: 13<br>Betweenness: 12.63<br>PageRank: 0.0233\",\"<b>Sentinel<\\/b><br>Degree: 16<br>Betweenness: 34.54<br>PageRank: 0.025\",\"<b>Osprey<\\/b><br>Degree: 3<br>Betweenness: 0<br>PageRank: 0.0088\",\"<b>Defender<\\/b><br>Degree: 4<br>Betweenness: 0<br>PageRank: 0.0065\",\"<b>Remora<\\/b><br>Degree: 21<br>Betweenness: 90.45<br>PageRank: 0.0409\",\"<b>Knowles<\\/b><br>Degree: 4<br>Betweenness: 0.5<br>PageRank: 0.0051\",\"<b>City Officials<\\/b><br>Degree: 1<br>Betweenness: 0<br>PageRank: 0.0066\",\"<b>Paackland Harbor<\\/b><br>Degree: 13<br>Betweenness: 27.08<br>PageRank: 0.0244\",\"<b>Haacklee Harbor<\\/b><br>Degree: 8<br>Betweenness: 41.3<br>PageRank: 0.0111\",\"<b>Himark Harbor<\\/b><br>Degree: 17<br>Betweenness: 52.61<br>PageRank: 0.0358\"],\"shape\":[\"dot\",\"dot\",\"dot\",\"dot\",\"dot\",\"dot\",\"dot\",\"dot\",\"dot\",\"dot\",\"square\",\"square\",\"square\",\"square\",\"triangle\",\"triangle\",\"triangle\",\"triangle\",\"triangle\",\"triangle\",\"triangle\",\"triangle\",\"triangle\",\"triangle\",\"triangle\",\"triangle\",\"diamond\",\"star\",\"star\",\"star\"],\"value\":[6.297086192940655,5.546984707878168,5.823674979714352,5.341903080060789,5.716727137412613,5.366531631035691,5.576625657577807,5.425218713427389,5.81696334194335,5.10587587464601,6.591393301385012,5.67208459997379,6.181213807960264,5.558266091317103,6.072999645744769,5.706400561681756,5.509799015300089,7.060723635120745,6.362444376099885,5.456949706479425,5.697659310767588,5.750152656749608,5.26252595678532,5.194958776160234,6.225537098067166,5.153050013669531,5.197080844534316,5.73335062064582,5.33299392251897,6.074440716571868]},\"edges\":{\"from\":[\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"4\",\"4\",\"4\",\"5\",\"5\",\"5\",\"5\",\"5\",\"6\",\"6\",\"6\",\"7\",\"7\",\"7\",\"7\",\"7\",\"7\",\"7\",\"7\",\"8\",\"8\",\"8\",\"8\",\"8\",\"8\",\"8\",\"15\",\"15\",\"15\",\"15\",\"15\",\"15\",\"16\",\"16\",\"16\",\"16\",\"17\",\"17\",\"17\",\"17\",\"18\",\"18\",\"18\",\"20\",\"20\",\"20\",\"20\",\"20\",\"20\",\"20\",\"20\",\"20\",\"20\",\"20\",\"20\",\"21\",\"21\",\"21\",\"21\",\"21\",\"21\",\"21\",\"21\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"23\",\"23\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"25\",\"25\",\"25\",\"25\",\"25\",\"26\",\"26\",\"26\",\"26\",\"27\",\"27\",\"27\",\"27\",\"27\",\"27\",\"27\",\"27\",\"27\",\"27\",\"27\",\"27\",\"27\",\"27\",\"27\",\"27\",\"28\",\"28\",\"28\",\"28\",\"28\",\"28\",\"28\",\"28\",\"28\",\"28\",\"28\",\"29\",\"29\",\"29\",\"29\",\"29\",\"29\",\"31\",\"31\",\"31\",\"31\",\"31\",\"31\",\"32\",\"32\",\"32\",\"32\",\"32\",\"32\",\"32\",\"33\",\"34\",\"34\",\"36\",\"36\",\"36\",\"36\",\"36\",\"36\",\"36\",\"36\",\"36\",\"37\",\"37\",\"37\",\"44\",\"44\",\"44\",\"44\",\"44\",\"44\",\"45\",\"45\",\"45\",\"45\",\"45\",\"45\",\"46\",\"46\",\"46\",\"46\",\"46\",\"46\"],\"to\":[\"5\",\"20\",\"22\",\"24\",\"25\",\"45\",\"3\",\"5\",\"22\",\"3\",\"4\",\"17\",\"20\",\"31\",\"20\",\"23\",\"27\",\"3\",\"7\",\"17\",\"22\",\"24\",\"27\",\"36\",\"46\",\"3\",\"7\",\"8\",\"15\",\"17\",\"23\",\"36\",\"16\",\"17\",\"22\",\"24\",\"27\",\"36\",\"5\",\"15\",\"17\",\"44\",\"15\",\"16\",\"22\",\"27\",\"7\",\"27\",\"36\",\"3\",\"5\",\"6\",\"20\",\"21\",\"25\",\"27\",\"28\",\"31\",\"32\",\"44\",\"46\",\"20\",\"21\",\"27\",\"28\",\"29\",\"31\",\"32\",\"44\",\"3\",\"4\",\"7\",\"8\",\"15\",\"17\",\"22\",\"24\",\"27\",\"36\",\"3\",\"36\",\"3\",\"4\",\"7\",\"22\",\"26\",\"27\",\"28\",\"36\",\"40\",\"46\",\"20\",\"27\",\"28\",\"36\",\"46\",\"24\",\"27\",\"28\",\"46\",\"4\",\"6\",\"7\",\"17\",\"20\",\"22\",\"23\",\"24\",\"25\",\"26\",\"28\",\"32\",\"33\",\"36\",\"44\",\"46\",\"20\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"31\",\"32\",\"34\",\"44\",\"20\",\"21\",\"27\",\"28\",\"31\",\"32\",\"5\",\"20\",\"28\",\"29\",\"31\",\"32\",\"3\",\"20\",\"21\",\"27\",\"28\",\"29\",\"44\",\"27\",\"27\",\"28\",\"3\",\"7\",\"8\",\"22\",\"23\",\"24\",\"27\",\"44\",\"46\",\"7\",\"27\",\"45\",\"5\",\"20\",\"27\",\"28\",\"32\",\"36\",\"3\",\"20\",\"27\",\"31\",\"33\",\"37\",\"20\",\"24\",\"25\",\"26\",\"27\",\"36\"]},\"nodesToDataframe\":true,\"edgesToDataframe\":true,\"options\":{\"width\":\"100%\",\"height\":\"100%\",\"nodes\":{\"shape\":\"dot\",\"scaling\":{\"min\":5,\"max\":30}},\"manipulation\":{\"enabled\":false},\"edges\":{\"arrows\":{\"to\":{\"enabled\":true,\"scaleFactor\":0.3}},\"color\":{\"color\":\"gray\"}},\"interaction\":{\"dragNodes\":false,\"dragView\":false,\"zoomView\":false,\"zoomSpeed\":1},\"layout\":{\"randomSeed\":123}},\"groups\":[\"Person\",\"Organization\",\"Vessel\",\"Group\",\"Location\"],\"width\":\"100%\",\"height\":\"700px\",\"idselection\":{\"enabled\":true,\"style\":\"width: 150px; height: 26px\",\"useLabels\":true,\"main\":\"Select by id\"},\"byselection\":{\"enabled\":false,\"style\":\"width: 150px; height: 26px\",\"multiple\":false,\"hideColor\":\"rgba(200,200,200,0.5)\",\"highlight\":false},\"main\":null,\"submain\":null,\"footer\":null,\"background\":\"rgba(0, 0, 0, 0)\",\"opts_manipulation\":{\"datacss\":\"table.legend_table {\\n  font-size: 11px;\\n  border-width:1px;\\n  border-color:#d3d3d3;\\n  border-style:solid;\\n}\\ntable.legend_table td {\\n  border-width:1px;\\n  border-color:#d3d3d3;\\n  border-style:solid;\\n  padding: 2px;\\n}\\ndiv.table_content {\\n  width:80px;\\n  text-align:center;\\n}\\ndiv.table_description {\\n  width:100px;\\n}\\n\\n.operation {\\n  font-size:20px;\\n}\\n\\n.network-popUp {\\n  display:none;\\n  z-index:299;\\n  width:250px;\\n  /*height:150px;*/\\n  background-color: #f9f9f9;\\n  border-style:solid;\\n  border-width:1px;\\n  border-color: #0d0d0d;\\n  padding:10px;\\n  text-align: center;\\n  position:fixed;\\n  top:50%;  \\n  left:50%;  \\n  margin:-100px 0 0 -100px;  \\n\\n}\",\"addNodeCols\":[\"id\",\"label\"],\"editNodeCols\":[\"id\",\"label\"],\"tab_add_node\":\"<span id=\\\"addnode-operation\\\" class = \\\"operation\\\">node<\\/span> <br><table style=\\\"margin:auto;\\\"><tr><td>id<\\/td><td><input id=\\\"addnode-id\\\"  type= \\\"text\\\" value=\\\"new value\\\"><\\/td><\\/tr><tr><td>label<\\/td><td><input id=\\\"addnode-label\\\"  type= \\\"text\\\" value=\\\"new value\\\"><\\/td><\\/tr><\\/table><input type=\\\"button\\\" value=\\\"save\\\" id=\\\"addnode-saveButton\\\"><\\/button><input type=\\\"button\\\" value=\\\"cancel\\\" id=\\\"addnode-cancelButton\\\"><\\/button>\",\"tab_edit_node\":\"<span id=\\\"editnode-operation\\\" class = \\\"operation\\\">node<\\/span> <br><table style=\\\"margin:auto;\\\"><tr><td>id<\\/td><td><input id=\\\"editnode-id\\\"  type= \\\"text\\\" value=\\\"new value\\\"><\\/td><\\/tr><tr><td>label<\\/td><td><input id=\\\"editnode-label\\\"  type= \\\"text\\\" value=\\\"new value\\\"><\\/td><\\/tr><\\/table><input type=\\\"button\\\" value=\\\"save\\\" id=\\\"editnode-saveButton\\\"><\\/button><input type=\\\"button\\\" value=\\\"cancel\\\" id=\\\"editnode-cancelButton\\\"><\\/button>\"},\"highlight\":{\"enabled\":true,\"hoverNearest\":false,\"degree\":1,\"algorithm\":\"all\",\"hideColor\":\"rgba(200,200,200,0.5)\",\"labelOnly\":true},\"collapse\":{\"enabled\":false,\"fit\":false,\"resetHighlight\":true,\"clusterOptions\":null,\"keepCoord\":true,\"labelSuffix\":\"(cluster)\"},\"tooltipStay\":300,\"tooltipStyle\":\"position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;font-family: verdana;font-size:14px;font-color:#000000;background-color: #f5f4ed;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;border: 1px solid #808074;box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);\",\"legend\":{\"width\":0.2,\"useGroups\":true,\"position\":\"left\",\"ncol\":1,\"stepX\":100,\"stepY\":100,\"zoom\":true}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n#### The Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nV(ego_graph)$name <- V(ego_graph)$name %||% V(ego_graph)$label\n\nnodes_df <- data.frame(\n  id = V(ego_graph)$name,\n  label = V(ego_graph)$label,\n  group = V(ego_graph)$sub_type,\n  title = paste0(\"<b>\", V(ego_graph)$label, \"</b><br>\",\n                 \"Degree: \", round(V(ego_graph)$degree, 2), \"<br>\",\n                 \"Betweenness: \", round(V(ego_graph)$betweenness, 2), \"<br>\",\n                 \"PageRank: \", round(V(ego_graph)$pagerank, 4)),\n  shape = \n    ifelse(V(ego_graph)$sub_type == \"Person\", \"dot\",\n                 ifelse(V(ego_graph)$sub_type == \"Organization\", \"square\",\n                        ifelse(V(ego_graph)$sub_type == \"Vessel\", \"triangle\",\n                               ifelse(V(ego_graph)$sub_type == \"Group\", \"diamond\", \"star\")))),\n  value = V(ego_graph)$pagerank * 30 + 5\n)\n\nedges_df <- as_data_frame(ego_graph, \n                          what = \"edges\") %>%\n  rename(from = from, \n         to = to)\n\nvisNetwork(nodes_df, edges_df, width = \"100%\", \n           height = \"700px\") %>%\n  visNodes(scaling = list(min = 5,\n                          max = 30)) %>%\n  visEdges(\n    arrows = list(to = list(enabled = TRUE, \n                            scaleFactor = 0.3)),\n    color = list(color = \"gray\")\n  ) %>%\n  visOptions(\n    highlightNearest = TRUE,\n    nodesIdSelection = TRUE,\n    manipulation = FALSE\n  ) %>%\n  visInteraction(\n    dragNodes = FALSE,\n    dragView = FALSE,\n    zoomView = FALSE\n  ) %>%\n  visLegend() %>%\n  visLayout(randomSeed = 123)\n```\n:::\n\n\n:::\n\n### 5.3.2 Quantitative analysis\n\n#### Individual indicator\n\nWe calculated three distinct centrality metrics — PageRank, Betweenness, and Degree — to independently assess the influence levels of each node.\n\nPageRank captures the importance of nodes based on the influence of their neighbors, Betweenness identifies key intermediaries controlling communication flow, and Degree measures the number of direct connections.\n\nBy presenting maximum and minimum rankings for each metric, we highlight which entities emerge as top influencers or least connected players depending on the chosen dimension. This granular view allows us to dissect influence from multiple structural perspectives rather than relying on a single indicator.\n\n::::: panel-tabset\n##### Maximum influence\n\n::: panel-tabset\n###### Pagerank\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nV(ego_1)$pagerank <- page_rank(ego_1)$vector\n\npagerank_df <- data.frame(\n  label = V(ego_1)$label,\n  sub_type = V(ego_1)$sub_type,\n  pagerank = round(V(ego_1)$pagerank, 4)\n) %>%\n  arrange(desc(pagerank))\n\nprint(pagerank_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               label     sub_type pagerank\n1            Neptune       Vessel   0.2333\n2 V. Miesel Shipping Organization   0.2244\n3        Nadia Conti       Person   0.1845\n4              Elise       Person   0.1289\n5               Mako       Vessel   0.1193\n6        Liam Thorne       Person   0.1096\n```\n\n\n:::\n:::\n\n\n\n###### Betweenness\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nV(ego_1)$betweenness <- betweenness(ego_1)\n\nbetweenness_df <- data.frame(\n  label = V(ego_1)$label,\n  sub_type = V(ego_1)$sub_type,\n  betweenness = round(V(ego_1)$betweenness, 2)\n) %>%\n  arrange(desc(betweenness))\n\nprint(betweenness_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               label     sub_type betweenness\n1        Nadia Conti       Person        4.30\n2            Neptune       Vessel        2.93\n3              Elise       Person        2.73\n4 V. Miesel Shipping Organization        1.82\n5        Liam Thorne       Person        0.22\n6               Mako       Vessel        0.00\n```\n\n\n:::\n:::\n\n\n\n###### Degree\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nV(ego_1)$degree <- degree(ego_1)\n\ndegree_df <- data.frame(\n  label = V(ego_1)$label,\n  sub_type = V(ego_1)$sub_type,\n  degree = V(ego_1)$degree\n) %>%\n  arrange(desc(degree))\n\nprint(degree_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               label     sub_type degree\n1            Neptune       Vessel     28\n2 V. Miesel Shipping Organization     22\n3               Mako       Vessel     13\n4        Nadia Conti       Person     12\n5              Elise       Person     11\n6        Liam Thorne       Person      6\n```\n\n\n:::\n:::\n\n\n:::\n\n##### Minimum influence\n\n::: panel-tabset\n###### Pagerank\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nV(g)$pagerank <- page_rank(g)$vector\n\npagerank_df <- data.frame(\n  label = V(g)$label,\n  sub_type = V(g)$sub_type,\n  pagerank = V(g)$pagerank\n)\n\nlowest_pagerank_df <- pagerank_df %>%\n  arrange(pagerank) %>%\n  slice(1:5)\n\nprint(lowest_pagerank_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       label     sub_type   pagerank\n1               Sailor Shift       Person 0.00345303\n2                  Small Fry       Person 0.00345303\n3              Glitters Team Organization 0.00345303\n4            Mariner's Dream       Vessel 0.00345303\n5 Recreational Fishing Boats        Group 0.00345303\n```\n\n\n:::\n:::\n\n\n\n###### Betweenness\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nV(g)$betweenness <- betweenness(g)\n\nbetweenness_df <- data.frame(\n  label = V(g)$label,\n  sub_type = V(g)$sub_type,\n  betweenness = V(g)$betweenness\n)\n\nlowest_betweenness_df <- betweenness_df %>%\n  arrange(betweenness) %>%\n  slice(1:5)\n\nprint(lowest_betweenness_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           label sub_type betweenness\n1          Kelly   Person           0\n2   Sailor Shift   Person           0\n3 Clepper Jensen   Person           0\n4 Miranda Jordan   Person           0\n5 The Accountant   Person           0\n```\n\n\n:::\n:::\n\n\n\n###### Degree\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nV(g)$degree <- degree(g, mode = \"all\")\n\ndegree_df <- data.frame(\n  label = V(g)$label,\n  sub_type = V(g)$sub_type,\n  degree = V(g)$degree\n)\n\nlowest_degree_df <- degree_df %>%\n  arrange(degree) %>%\n  slice(1:5)\n\nprint(lowest_degree_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       label sub_type degree\n1               Sailor Shift   Person      0\n2            Mariner's Dream   Vessel      0\n3 Recreational Fishing Boats    Group      0\n4      Diving Tour Operators    Group      0\n5                   Tourists    Group      0\n```\n\n\n:::\n:::\n\n\n:::\n:::::\n\n#### Composite Influence Score\n\nTo create a holistic measure of influence, we normalized each centrality metric (PageRank, Betweenness, Degree) to a 0–1 scale and computed a composite score by averaging the three. This composite influence score integrates local connectivity, intermediary control, and overall network importance, providing a balanced ranking of key players.\n\nBy combining metrics, we mitigate the bias of any single indicator and gain a clearer picture of which entities exert the most multifaceted influence in the network, guiding more robust identification of central figures like Neptune, V. Miesel Shipping, and Nadia Conti.\n\n::: panel-tabset\n##### The Table\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n               label     sub_type pagerank_norm betweenness_norm degree_norm\n1            Neptune       Vessel    1.00000000       0.68164286   1.0000000\n2 V. Miesel Shipping Organization    0.92812469       0.42254762   0.7272727\n3        Nadia Conti       Person    0.60499493       1.00000000   0.2727273\n4              Elise       Person    0.15540452       0.63414286   0.2272727\n5               Mako       Vessel    0.07796095       0.00000000   0.3181818\n6        Liam Thorne       Person    0.00000000       0.05166667   0.0000000\n  composite_influence\n1          0.89388095\n2          0.69264834\n3          0.62590740\n4          0.33894003\n5          0.13204759\n6          0.01722222\n```\n\n\n:::\n:::\n\n\n\n##### The Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nV(ego_1)$pagerank <- page_rank(ego_1)$vector\nV(ego_1)$betweenness <- betweenness(ego_1)\nV(ego_1)$degree <- degree(ego_1)\n\ninfluence_df <- data.frame(\n  label = V(ego_1)$label,\n  sub_type = V(ego_1)$sub_type,\n  pagerank = V(ego_1)$pagerank,\n  betweenness = V(ego_1)$betweenness,\n  degree = V(ego_1)$degree\n)\n\ninfluence_df <- influence_df %>%\n  mutate(\n    pagerank_norm = (pagerank - min(pagerank)) / (max(pagerank) - min(pagerank)),\n    betweenness_norm = (betweenness - min(betweenness)) / (max(betweenness) - min(betweenness)),\n    degree_norm = (degree - min(degree)) / (max(degree) - min(degree))\n  )\n\ninfluence_df <- influence_df %>%\n  mutate(\n    composite_influence = (pagerank_norm + betweenness_norm + degree_norm) / 3\n  ) %>%\n  arrange(desc(composite_influence))\n\nprint(influence_df %>%\n  select(label, sub_type, pagerank_norm, betweenness_norm, degree_norm, composite_influence))\n```\n:::\n\n\n:::\n\n### 5.3.3PageRank for Elise\n\n::: panel-tabset\n#### The Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-3457bd1e51be2b259444\" style=\"width:100%;height:400px;\" class=\"visNetwork html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-3457bd1e51be2b259444\">{\"x\":{\"nodes\":{\"id\":[\"3\",\"4\",\"5\",\"22\",\"24\",\"27\"],\"label\":[\"Nadia Conti\",\"Elise\",\"Liam Thorne\",\"V. Miesel Shipping\",\"Neptune\",\"Mako\"],\"group\":[\"Person\",\"Person\",\"Person\",\"Organization\",\"Vessel\",\"Vessel\"],\"title\":[\"<b>Nadia Conti<\\/b><br>PageRank: 0.1845\",\"<b>Elise<\\/b><br>PageRank: 0.1289\",\"<b>Liam Thorne<\\/b><br>PageRank: 0.1096\",\"<b>V. Miesel Shipping<\\/b><br>PageRank: 0.2244\",\"<b>Neptune<\\/b><br>PageRank: 0.2333\",\"<b>Mako<\\/b><br>PageRank: 0.1193\"],\"shape\":[\"dot\",\"dot\",\"dot\",\"square\",\"triangle\",\"triangle\"],\"value\":[10.53412448971907,8.865509108650544,8.288738874975076,11.73339225275303,12.00015117771245,8.578084096189841]},\"edges\":{\"from\":[\"3\",\"3\",\"3\",\"3\",\"3\",\"4\",\"4\",\"4\",\"4\",\"4\",\"5\",\"5\",\"5\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"27\",\"27\",\"27\",\"27\",\"27\"],\"to\":[\"5\",\"5\",\"22\",\"24\",\"24\",\"3\",\"3\",\"3\",\"5\",\"22\",\"3\",\"3\",\"4\",\"3\",\"4\",\"22\",\"22\",\"24\",\"24\",\"24\",\"24\",\"27\",\"3\",\"4\",\"4\",\"4\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"27\",\"27\",\"27\",\"27\",\"27\",\"27\",\"27\",\"4\",\"22\",\"24\",\"24\",\"24\"]},\"nodesToDataframe\":true,\"edgesToDataframe\":true,\"options\":{\"width\":\"100%\",\"height\":\"100%\",\"nodes\":{\"shape\":\"dot\",\"scaling\":{\"min\":5,\"max\":30}},\"manipulation\":{\"enabled\":false},\"edges\":{\"arrows\":{\"to\":{\"enabled\":true,\"scaleFactor\":0.3}},\"color\":{\"color\":\"gray\"}},\"interaction\":{\"dragNodes\":false,\"dragView\":false,\"zoomView\":false,\"zoomSpeed\":1},\"layout\":{\"randomSeed\":123}},\"groups\":[\"Person\",\"Organization\",\"Vessel\"],\"width\":\"100%\",\"height\":\"400px\",\"idselection\":{\"enabled\":true,\"style\":\"width: 150px; height: 26px\",\"useLabels\":true,\"main\":\"Select by id\"},\"byselection\":{\"enabled\":false,\"style\":\"width: 150px; height: 26px\",\"multiple\":false,\"hideColor\":\"rgba(200,200,200,0.5)\",\"highlight\":false},\"main\":null,\"submain\":null,\"footer\":null,\"background\":\"rgba(0, 0, 0, 0)\",\"opts_manipulation\":{\"datacss\":\"table.legend_table {\\n  font-size: 11px;\\n  border-width:1px;\\n  border-color:#d3d3d3;\\n  border-style:solid;\\n}\\ntable.legend_table td {\\n  border-width:1px;\\n  border-color:#d3d3d3;\\n  border-style:solid;\\n  padding: 2px;\\n}\\ndiv.table_content {\\n  width:80px;\\n  text-align:center;\\n}\\ndiv.table_description {\\n  width:100px;\\n}\\n\\n.operation {\\n  font-size:20px;\\n}\\n\\n.network-popUp {\\n  display:none;\\n  z-index:299;\\n  width:250px;\\n  /*height:150px;*/\\n  background-color: #f9f9f9;\\n  border-style:solid;\\n  border-width:1px;\\n  border-color: #0d0d0d;\\n  padding:10px;\\n  text-align: center;\\n  position:fixed;\\n  top:50%;  \\n  left:50%;  \\n  margin:-100px 0 0 -100px;  \\n\\n}\",\"addNodeCols\":[\"id\",\"label\"],\"editNodeCols\":[\"id\",\"label\"],\"tab_add_node\":\"<span id=\\\"addnode-operation\\\" class = \\\"operation\\\">node<\\/span> <br><table style=\\\"margin:auto;\\\"><tr><td>id<\\/td><td><input id=\\\"addnode-id\\\"  type= \\\"text\\\" value=\\\"new value\\\"><\\/td><\\/tr><tr><td>label<\\/td><td><input id=\\\"addnode-label\\\"  type= \\\"text\\\" value=\\\"new value\\\"><\\/td><\\/tr><\\/table><input type=\\\"button\\\" value=\\\"save\\\" id=\\\"addnode-saveButton\\\"><\\/button><input type=\\\"button\\\" value=\\\"cancel\\\" id=\\\"addnode-cancelButton\\\"><\\/button>\",\"tab_edit_node\":\"<span id=\\\"editnode-operation\\\" class = \\\"operation\\\">node<\\/span> <br><table style=\\\"margin:auto;\\\"><tr><td>id<\\/td><td><input id=\\\"editnode-id\\\"  type= \\\"text\\\" value=\\\"new value\\\"><\\/td><\\/tr><tr><td>label<\\/td><td><input id=\\\"editnode-label\\\"  type= \\\"text\\\" value=\\\"new value\\\"><\\/td><\\/tr><\\/table><input type=\\\"button\\\" value=\\\"save\\\" id=\\\"editnode-saveButton\\\"><\\/button><input type=\\\"button\\\" value=\\\"cancel\\\" id=\\\"editnode-cancelButton\\\"><\\/button>\"},\"highlight\":{\"enabled\":true,\"hoverNearest\":false,\"degree\":1,\"algorithm\":\"all\",\"hideColor\":\"rgba(200,200,200,0.5)\",\"labelOnly\":true},\"collapse\":{\"enabled\":false,\"fit\":false,\"resetHighlight\":true,\"clusterOptions\":null,\"keepCoord\":true,\"labelSuffix\":\"(cluster)\"},\"tooltipStay\":300,\"tooltipStyle\":\"position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;font-family: verdana;font-size:14px;font-color:#000000;background-color: #f5f4ed;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;border: 1px solid #808074;box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);\",\"legend\":{\"width\":0.2,\"useGroups\":true,\"position\":\"left\",\"ncol\":1,\"stepX\":100,\"stepY\":100,\"zoom\":true}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n#### The Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ego-PageRank\nV(ego_1)$pagerank <- page_rank(ego_1)$vector\n\nnodes_df_pagerank <- data.frame(\n  id = V(ego_1)$name,\n  label = V(ego_1)$label,\n  group = V(ego_1)$sub_type,\n  title = paste0(\"<b>\", V(ego_1)$label, \"</b><br>PageRank: \", round(V(ego_1)$pagerank, 4)),\n  shape = ifelse(V(ego_1)$sub_type == \"Person\", \"dot\",\n                 ifelse(V(ego_1)$sub_type == \"Organization\", \"square\",\n                        ifelse(V(ego_1)$sub_type == \"Vessel\", \"triangle\",\n                               ifelse(V(ego_1)$sub_type == \"Group\", \"diamond\", \"star\")))),\n  value = V(ego_1)$pagerank * 30 + 5\n)\n\nedges_df <- as_data_frame(ego_1, what = \"edges\") %>%\n  rename(from = from, to = to)\n\nvisNetwork(nodes_df_pagerank, edges_df, width = \"100%\", height = \"400px\") %>%\n  visNodes(scaling = list(min = 5, max = 30)) %>%\n  visEdges(arrows = list(to = list(enabled = TRUE, scaleFactor = 0.3)), color = list(color = \"gray\")) %>%\n  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE, manipulation = FALSE) %>%\n  visInteraction(dragNodes = FALSE, dragView = FALSE, zoomView = FALSE) %>%\n  visLegend() %>%\n  visLayout(randomSeed = 123)\n```\n:::\n\n\n:::\n\n### 5.3.4 Betweenness for Elise\n\n::: panel-tabset\n#### The Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-7c4077752db44111f2bd\" style=\"width:100%;height:400px;\" class=\"visNetwork html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-7c4077752db44111f2bd\">{\"x\":{\"nodes\":{\"id\":[\"3\",\"4\",\"5\",\"22\",\"24\",\"27\"],\"label\":[\"Nadia Conti\",\"Elise\",\"Liam Thorne\",\"V. Miesel Shipping\",\"Neptune\",\"Mako\"],\"group\":[\"Person\",\"Person\",\"Person\",\"Organization\",\"Vessel\",\"Vessel\"],\"title\":[\"<b>Nadia Conti<\\/b><br>Betweenness: 4.3\",\"<b>Elise<\\/b><br>Betweenness: 2.73\",\"<b>Liam Thorne<\\/b><br>Betweenness: 0.22\",\"<b>V. Miesel Shipping<\\/b><br>Betweenness: 1.82\",\"<b>Neptune<\\/b><br>Betweenness: 2.93\",\"<b>Mako<\\/b><br>Betweenness: 0\"],\"shape\":[\"dot\",\"dot\",\"dot\",\"square\",\"triangle\",\"triangle\"],\"value\":[13.60215053763441,10.45499231950845,5.444444444444445,8.634818228366616,10.86359447004608,5]},\"edges\":{\"from\":[\"3\",\"3\",\"3\",\"3\",\"3\",\"4\",\"4\",\"4\",\"4\",\"4\",\"5\",\"5\",\"5\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"27\",\"27\",\"27\",\"27\",\"27\"],\"to\":[\"5\",\"5\",\"22\",\"24\",\"24\",\"3\",\"3\",\"3\",\"5\",\"22\",\"3\",\"3\",\"4\",\"3\",\"4\",\"22\",\"22\",\"24\",\"24\",\"24\",\"24\",\"27\",\"3\",\"4\",\"4\",\"4\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"27\",\"27\",\"27\",\"27\",\"27\",\"27\",\"27\",\"4\",\"22\",\"24\",\"24\",\"24\"]},\"nodesToDataframe\":true,\"edgesToDataframe\":true,\"options\":{\"width\":\"100%\",\"height\":\"100%\",\"nodes\":{\"shape\":\"dot\",\"scaling\":{\"min\":5,\"max\":30}},\"manipulation\":{\"enabled\":false},\"edges\":{\"arrows\":{\"to\":{\"enabled\":true,\"scaleFactor\":0.3}},\"color\":{\"color\":\"gray\"}},\"interaction\":{\"dragNodes\":false,\"dragView\":false,\"zoomView\":false,\"zoomSpeed\":1},\"layout\":{\"randomSeed\":123}},\"groups\":[\"Person\",\"Organization\",\"Vessel\"],\"width\":\"100%\",\"height\":\"400px\",\"idselection\":{\"enabled\":true,\"style\":\"width: 150px; height: 26px\",\"useLabels\":true,\"main\":\"Select by id\"},\"byselection\":{\"enabled\":false,\"style\":\"width: 150px; height: 26px\",\"multiple\":false,\"hideColor\":\"rgba(200,200,200,0.5)\",\"highlight\":false},\"main\":null,\"submain\":null,\"footer\":null,\"background\":\"rgba(0, 0, 0, 0)\",\"opts_manipulation\":{\"datacss\":\"table.legend_table {\\n  font-size: 11px;\\n  border-width:1px;\\n  border-color:#d3d3d3;\\n  border-style:solid;\\n}\\ntable.legend_table td {\\n  border-width:1px;\\n  border-color:#d3d3d3;\\n  border-style:solid;\\n  padding: 2px;\\n}\\ndiv.table_content {\\n  width:80px;\\n  text-align:center;\\n}\\ndiv.table_description {\\n  width:100px;\\n}\\n\\n.operation {\\n  font-size:20px;\\n}\\n\\n.network-popUp {\\n  display:none;\\n  z-index:299;\\n  width:250px;\\n  /*height:150px;*/\\n  background-color: #f9f9f9;\\n  border-style:solid;\\n  border-width:1px;\\n  border-color: #0d0d0d;\\n  padding:10px;\\n  text-align: center;\\n  position:fixed;\\n  top:50%;  \\n  left:50%;  \\n  margin:-100px 0 0 -100px;  \\n\\n}\",\"addNodeCols\":[\"id\",\"label\"],\"editNodeCols\":[\"id\",\"label\"],\"tab_add_node\":\"<span id=\\\"addnode-operation\\\" class = \\\"operation\\\">node<\\/span> <br><table style=\\\"margin:auto;\\\"><tr><td>id<\\/td><td><input id=\\\"addnode-id\\\"  type= \\\"text\\\" value=\\\"new value\\\"><\\/td><\\/tr><tr><td>label<\\/td><td><input id=\\\"addnode-label\\\"  type= \\\"text\\\" value=\\\"new value\\\"><\\/td><\\/tr><\\/table><input type=\\\"button\\\" value=\\\"save\\\" id=\\\"addnode-saveButton\\\"><\\/button><input type=\\\"button\\\" value=\\\"cancel\\\" id=\\\"addnode-cancelButton\\\"><\\/button>\",\"tab_edit_node\":\"<span id=\\\"editnode-operation\\\" class = \\\"operation\\\">node<\\/span> <br><table style=\\\"margin:auto;\\\"><tr><td>id<\\/td><td><input id=\\\"editnode-id\\\"  type= \\\"text\\\" value=\\\"new value\\\"><\\/td><\\/tr><tr><td>label<\\/td><td><input id=\\\"editnode-label\\\"  type= \\\"text\\\" value=\\\"new value\\\"><\\/td><\\/tr><\\/table><input type=\\\"button\\\" value=\\\"save\\\" id=\\\"editnode-saveButton\\\"><\\/button><input type=\\\"button\\\" value=\\\"cancel\\\" id=\\\"editnode-cancelButton\\\"><\\/button>\"},\"highlight\":{\"enabled\":true,\"hoverNearest\":false,\"degree\":1,\"algorithm\":\"all\",\"hideColor\":\"rgba(200,200,200,0.5)\",\"labelOnly\":true},\"collapse\":{\"enabled\":false,\"fit\":false,\"resetHighlight\":true,\"clusterOptions\":null,\"keepCoord\":true,\"labelSuffix\":\"(cluster)\"},\"tooltipStay\":300,\"tooltipStyle\":\"position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;font-family: verdana;font-size:14px;font-color:#000000;background-color: #f5f4ed;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;border: 1px solid #808074;box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);\",\"legend\":{\"width\":0.2,\"useGroups\":true,\"position\":\"left\",\"ncol\":1,\"stepX\":100,\"stepY\":100,\"zoom\":true}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n#### The code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ego-Betweenness\nV(ego_1)$betweenness <- betweenness(ego_1)\n\nnodes_df_betweenness <- data.frame(\n  id = V(ego_1)$name,\n  label = V(ego_1)$label,\n  group = V(ego_1)$sub_type,\n  title = paste0(\"<b>\", V(ego_1)$label, \"</b><br>Betweenness: \", round(V(ego_1)$betweenness, 2)),\n  shape = ifelse(V(ego_1)$sub_type == \"Person\", \"dot\",\n                 ifelse(V(ego_1)$sub_type == \"Organization\", \"square\",\n                        ifelse(V(ego_1)$sub_type == \"Vessel\", \"triangle\",\n                               ifelse(V(ego_1)$sub_type == \"Group\", \"diamond\", \"star\")))),\n  value = V(ego_1)$betweenness * 2 + 5\n)\n\nvisNetwork(nodes_df_betweenness, edges_df, width = \"100%\", height = \"400px\") %>%\n  visNodes(scaling = list(min = 5, max = 30)) %>%\n  visEdges(arrows = list(to = list(enabled = TRUE, scaleFactor = 0.3)), color = list(color = \"gray\")) %>%\n  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE, manipulation = FALSE) %>%\n  visInteraction(dragNodes = FALSE, dragView = FALSE, zoomView = FALSE) %>%\n  visLegend() %>%\n  visLayout(randomSeed = 123)\n```\n:::\n\n\n:::\n\n### 5.3.5 Degree for Elise\n\n::: panel-tabset\n#### The Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-9346805b528e1e9e1419\" style=\"width:100%;height:400px;\" class=\"visNetwork html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-9346805b528e1e9e1419\">{\"x\":{\"nodes\":{\"id\":[\"3\",\"4\",\"5\",\"22\",\"24\",\"27\"],\"label\":[\"Nadia Conti\",\"Elise\",\"Liam Thorne\",\"V. Miesel Shipping\",\"Neptune\",\"Mako\"],\"group\":[\"Person\",\"Person\",\"Person\",\"Organization\",\"Vessel\",\"Vessel\"],\"title\":[\"<b>Nadia Conti<\\/b><br>Degree: 12\",\"<b>Elise<\\/b><br>Degree: 11\",\"<b>Liam Thorne<\\/b><br>Degree: 6\",\"<b>V. Miesel Shipping<\\/b><br>Degree: 22\",\"<b>Neptune<\\/b><br>Degree: 28\",\"<b>Mako<\\/b><br>Degree: 13\"],\"shape\":[\"dot\",\"dot\",\"dot\",\"square\",\"triangle\",\"triangle\"],\"value\":[60,55,30,110,140,65]},\"edges\":{\"from\":[\"3\",\"3\",\"3\",\"3\",\"3\",\"4\",\"4\",\"4\",\"4\",\"4\",\"5\",\"5\",\"5\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"24\",\"27\",\"27\",\"27\",\"27\",\"27\"],\"to\":[\"5\",\"5\",\"22\",\"24\",\"24\",\"3\",\"3\",\"3\",\"5\",\"22\",\"3\",\"3\",\"4\",\"3\",\"4\",\"22\",\"22\",\"24\",\"24\",\"24\",\"24\",\"27\",\"3\",\"4\",\"4\",\"4\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"22\",\"27\",\"27\",\"27\",\"27\",\"27\",\"27\",\"27\",\"4\",\"22\",\"24\",\"24\",\"24\"]},\"nodesToDataframe\":true,\"edgesToDataframe\":true,\"options\":{\"width\":\"100%\",\"height\":\"100%\",\"nodes\":{\"shape\":\"dot\",\"scaling\":{\"min\":5,\"max\":30}},\"manipulation\":{\"enabled\":false},\"edges\":{\"arrows\":{\"to\":{\"enabled\":true,\"scaleFactor\":0.3}},\"color\":{\"color\":\"gray\"}},\"interaction\":{\"dragNodes\":false,\"dragView\":false,\"zoomView\":false,\"zoomSpeed\":1},\"layout\":{\"randomSeed\":123}},\"groups\":[\"Person\",\"Organization\",\"Vessel\"],\"width\":\"100%\",\"height\":\"400px\",\"idselection\":{\"enabled\":true,\"style\":\"width: 150px; height: 26px\",\"useLabels\":true,\"main\":\"Select by id\"},\"byselection\":{\"enabled\":false,\"style\":\"width: 150px; height: 26px\",\"multiple\":false,\"hideColor\":\"rgba(200,200,200,0.5)\",\"highlight\":false},\"main\":null,\"submain\":null,\"footer\":null,\"background\":\"rgba(0, 0, 0, 0)\",\"opts_manipulation\":{\"datacss\":\"table.legend_table {\\n  font-size: 11px;\\n  border-width:1px;\\n  border-color:#d3d3d3;\\n  border-style:solid;\\n}\\ntable.legend_table td {\\n  border-width:1px;\\n  border-color:#d3d3d3;\\n  border-style:solid;\\n  padding: 2px;\\n}\\ndiv.table_content {\\n  width:80px;\\n  text-align:center;\\n}\\ndiv.table_description {\\n  width:100px;\\n}\\n\\n.operation {\\n  font-size:20px;\\n}\\n\\n.network-popUp {\\n  display:none;\\n  z-index:299;\\n  width:250px;\\n  /*height:150px;*/\\n  background-color: #f9f9f9;\\n  border-style:solid;\\n  border-width:1px;\\n  border-color: #0d0d0d;\\n  padding:10px;\\n  text-align: center;\\n  position:fixed;\\n  top:50%;  \\n  left:50%;  \\n  margin:-100px 0 0 -100px;  \\n\\n}\",\"addNodeCols\":[\"id\",\"label\"],\"editNodeCols\":[\"id\",\"label\"],\"tab_add_node\":\"<span id=\\\"addnode-operation\\\" class = \\\"operation\\\">node<\\/span> <br><table style=\\\"margin:auto;\\\"><tr><td>id<\\/td><td><input id=\\\"addnode-id\\\"  type= \\\"text\\\" value=\\\"new value\\\"><\\/td><\\/tr><tr><td>label<\\/td><td><input id=\\\"addnode-label\\\"  type= \\\"text\\\" value=\\\"new value\\\"><\\/td><\\/tr><\\/table><input type=\\\"button\\\" value=\\\"save\\\" id=\\\"addnode-saveButton\\\"><\\/button><input type=\\\"button\\\" value=\\\"cancel\\\" id=\\\"addnode-cancelButton\\\"><\\/button>\",\"tab_edit_node\":\"<span id=\\\"editnode-operation\\\" class = \\\"operation\\\">node<\\/span> <br><table style=\\\"margin:auto;\\\"><tr><td>id<\\/td><td><input id=\\\"editnode-id\\\"  type= \\\"text\\\" value=\\\"new value\\\"><\\/td><\\/tr><tr><td>label<\\/td><td><input id=\\\"editnode-label\\\"  type= \\\"text\\\" value=\\\"new value\\\"><\\/td><\\/tr><\\/table><input type=\\\"button\\\" value=\\\"save\\\" id=\\\"editnode-saveButton\\\"><\\/button><input type=\\\"button\\\" value=\\\"cancel\\\" id=\\\"editnode-cancelButton\\\"><\\/button>\"},\"highlight\":{\"enabled\":true,\"hoverNearest\":false,\"degree\":1,\"algorithm\":\"all\",\"hideColor\":\"rgba(200,200,200,0.5)\",\"labelOnly\":true},\"collapse\":{\"enabled\":false,\"fit\":false,\"resetHighlight\":true,\"clusterOptions\":null,\"keepCoord\":true,\"labelSuffix\":\"(cluster)\"},\"tooltipStay\":300,\"tooltipStyle\":\"position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;font-family: verdana;font-size:14px;font-color:#000000;background-color: #f5f4ed;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;border: 1px solid #808074;box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);\",\"legend\":{\"width\":0.2,\"useGroups\":true,\"position\":\"left\",\"ncol\":1,\"stepX\":100,\"stepY\":100,\"zoom\":true}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n#### The Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ego-Degree\nV(ego_1)$degree <- degree(ego_1)\n\nnodes_df_degree <- data.frame(\n  id = V(ego_1)$name,\n  label = V(ego_1)$label,\n  group = V(ego_1)$sub_type,\n  title = paste0(\"<b>\", V(ego_1)$label, \"</b><br>Degree: \", round(V(ego_1)$degree, 2)),\n  shape = ifelse(V(ego_1)$sub_type == \"Person\", \"dot\",\n                 ifelse(V(ego_1)$sub_type == \"Organization\", \"square\",\n                        ifelse(V(ego_1)$sub_type == \"Vessel\", \"triangle\",\n                               ifelse(V(ego_1)$sub_type == \"Group\", \"diamond\", \"star\")))),\n  value = V(ego_1)$degree * 5\n)\n\nvisNetwork(nodes_df_degree, edges_df, width = \"100%\", height = \"400px\") %>%\n  visNodes(scaling = list(min = 5, max = 30)) %>%\n  visEdges(arrows = list(to = list(enabled = TRUE, scaleFactor = 0.3)), color = list(color = \"gray\")) %>%\n  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE, manipulation = FALSE) %>%\n  visInteraction(dragNodes = FALSE, dragView = FALSE, zoomView = FALSE) %>%\n  visLegend() %>%\n  visLayout(randomSeed = 123)\n```\n:::\n\n\n:::\n\n::: {.callout-tip title=\"Insight\"}\n-   By combining global network visualization and centrality metric analysis, we systematically identified Elise’s position in the network and her primary sources of influence. The overall knowledge graph reveals that Elise is embedded within a complex web of relationships involving key individuals (such as Nadia Conti), major organizations (such as V. Miesel Shipping), and important vessels (such as Neptune). These entities not only occupy central positions in the network but also deeply shape Elise’s connections and the flow of information around her.\n\n-   Through single-metric centrality analysis, we further uncover Elise’s direct and indirect influences. Degree centrality shows that Neptune has the highest number of direct connections (28), followed by V. Miesel Shipping (22), while Elise herself has a Degree of 11, ranking fifth. This indicates that while Elise is not the most directly active node, she maintains close ties with highly active hub nodes.\n\n-   From the perspective of Betweenness centrality, Nadia Conti ranks first with a value of 4.30, followed by Neptune at 2.93, and Elise at 2.73 in third place. This means that Nadia Conti is the most important intermediary and information bridge in Elise’s communication pathways, with strong influence over how Elise accesses and disseminates information.\n\n-   PageRank analysis emphasizes overall node influence. Neptune ranks first at 0.2333, closely followed by V. Miesel Shipping at 0.2244, and Nadia Conti at 0.1845. This suggests that the higher-level nodes Elise is connected to—particularly Neptune and V. Miesel Shipping—hold powerful network positions, exerting significant influence over Elise.\n\n-   To further quantify influence, we combined these three centrality metrics—PageRank, Betweenness, and Degree—into a composite influence score after normalization. The results show that Neptune is the most influential node within Elise’s network (0.89), followed by V. Miesel Shipping (0.69) and Nadia Conti (0.63). Although Elise’s own scores across PageRank, Betweenness, and Degree are moderate to low, her core interaction partners are consistently the top-ranking entities in composite influence.\n:::\n\n# 6 Reference\n\n-   [**VAST 2024 Mini Challenge 3**](https://vast-challenge.github.io/2025/MC3.html)\n-   [**R for Visual Analytics**](https://r4va.netlify.app)\n-   [**The Big Fish: Catching Illegal Fishing Through Visual Analytics**](https://isss608-202324g4.netlify.app)\n",
    "supporting": [
      "Take-home_Ex02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/vis-9.1.0/vis-network.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/vis-9.1.0/vis-network.min.js\"></script>\n<script src=\"../../site_libs/visNetwork-binding-2.1.2/visNetwork.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}